services:
  siglip-api:
    build: .
    container_name: siglip-api
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/app/cache
    volumes:
      - model_cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 16G
        reservations:
          cpus: '16'
          memory: 16G
    networks:
      - trg-network-external 

networks:
  trg-network-external:
    name: master_trg-network
    external: true 

volumes:
  model_cache:

